# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-updated']},
        ),
    ]
